### ISSUE TITLE
node stack overflow error

### ISSUE THREAD

**Issue by dktanwar** [renozao/NMF#45]
I am getting following error while using plotting the calculated results from NMF package.

 

> dim(data)

# 12831 36

> res <- nmf(x = data, rank = 2)

> basismap(res)

# Error in match(x, table, nomatch = 0L) : node stack overflow

> sessionInfo()
                                                                                                                                                                         
R version 3.1.3 (2015-03-09)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] RColorBrewer_1.1-2  doParallel_1.0.8    iterators_1.0.7
 [4] foreach_1.4.2       NMF_0.20.6          synchronicity_1.1.4
 [7] bigmemory_4.4.6     BH_1.58.0-1         bigmemory.sri_0.1.3
[10] Biobase_2.26.0      BiocGenerics_0.12.1 cluster_2.0.2
[13] rngtools_1.2.4      pkgmaker_0.22       registry_0.3

loaded via a namespace (and not attached):
 [1] codetools_0.2-11 colorspace_1.2-6 compiler_3.1.3   digest_0.6.8
 [5] ggplot2_1.0.1    grid_3.1.3       gridBase_0.4-7   gtable_0.1.2
 [9] magrittr_1.5     MASS_7.3-42      munsell_0.4.2    plyr_1.8.3
[13] proto_0.3-10     Rcpp_0.11.6      reshape2_1.4.1   scales_0.2.5
[17] stringi_0.5-5    stringr_1.0.0    tools_3.1.3      xtable_1.7-4

**Comment by renozao** [comment]
This is probably because the dendrogram R base plotting function breaks with such a large number of rows, which is (was) a known issue, due to the recursivity of the workhorse function `plotNode`. 
This was fortunately solved in R 3.2.1. I checked it on my side with a random NMF model of the same dimension (Ubuntu linux) and it does not break. 

See:
http://cran.r-project.org/doc/manuals/r-release/NEWS.html
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=15215

**Comment by dktanwar** [comment]
Hi,
It is not solved for me yet 

res_2 <- nmf(x = short_bi, rank = 2, nrun = 50, .opt = "vp16")
NMF algorithm: 'brunet'
Multiple runs: 50
Mode: parallel (16/64 core(s))
Runs: |==================================================| 100%
System time:
   user  system elapsed
300.854  13.484  28.333

dim(short_bi)
[1] 12851    36

basismap(res_2)
nmfAlgoriError in structure(r, class = "dendrogram") : node stack overflow

> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] doParallel_1.0.8    iterators_1.0.7     foreach_1.4.2
 [4] NMF_0.20.6          synchronicity_1.1.4 bigmemory_4.4.6
 [7] BH_1.58.0-1         bigmemory.sri_0.1.3 Biobase_2.28.0
[10] BiocGenerics_0.14.0 cluster_2.0.2       rngtools_1.2.4
[13] pkgmaker_0.22       registry_0.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6        magrittr_1.5       MASS_7.3-42        munsell_0.4.2
 [5] colorspace_1.2-6   xtable_1.7-4       gridBase_0.4-7     stringr_1.0.0
 [9] plyr_1.8.3         tools_3.2.1        grid_3.2.1         gtable_0.1.2
[13] digest_0.6.8       RColorBrewer_1.1-2 reshape2_1.4.1     ggplot2_1.0.1
[17] codetools_0.2-11   stringi_0.5-5      compiler_3.2.1     scales_0.2.5
[21] proto_0.3-10

**Comment by renozao** [comment]
I tested it on the `devel` version (from github) with:

```R
set.seed(12345)
x <- rnmf(2, 12851, 36)
basismap(x)
```
